from widgets.settings_dialog import Ui_SettingsDialog
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from cube import cube
import torch
from networks.getNetwork import getNetwork
from widgets import widgets_utils
from search.search import AStar
from cube.cube import clear_seq


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, conf):
        self.conf = conf
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 2, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 2, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cubie_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_20.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_20.sizePolicy().hasHeightForWidth())
        self.cubie_20.setSizePolicy(sizePolicy)
        self.cubie_20.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_20.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_20.setStyleSheet("background-color:white;\n"
"")
        self.cubie_20.setObjectName("cubie_20")
        self.gridLayout_3.addWidget(self.cubie_20, 0, 2, 1, 1)
        self.cubie_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_22.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_22.sizePolicy().hasHeightForWidth())
        self.cubie_22.setSizePolicy(sizePolicy)
        self.cubie_22.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_22.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_22.setStyleSheet("background-color:white;\n"
"")
        self.cubie_22.setObjectName("cubie_22")
        self.gridLayout_3.addWidget(self.cubie_22, 1, 1, 1, 1)
        self.cubie_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_21.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_21.sizePolicy().hasHeightForWidth())
        self.cubie_21.setSizePolicy(sizePolicy)
        self.cubie_21.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_21.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_21.setStyleSheet("background-color:white;\n"
"")
        self.cubie_21.setObjectName("cubie_21")
        self.gridLayout_3.addWidget(self.cubie_21, 1, 0, 1, 1)
        self.cubie_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_23.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_23.sizePolicy().hasHeightForWidth())
        self.cubie_23.setSizePolicy(sizePolicy)
        self.cubie_23.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_23.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_23.setStyleSheet("background-color:white;\n"
"")
        self.cubie_23.setObjectName("cubie_23")
        self.gridLayout_3.addWidget(self.cubie_23, 1, 2, 1, 1)
        self.cubie_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_19.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_19.sizePolicy().hasHeightForWidth())
        self.cubie_19.setSizePolicy(sizePolicy)
        self.cubie_19.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_19.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_19.setStyleSheet("background-color:white;\n"
"")
        self.cubie_19.setObjectName("cubie_19")
        self.gridLayout_3.addWidget(self.cubie_19, 0, 1, 1, 1)
        self.cubie_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_18.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_18.sizePolicy().hasHeightForWidth())
        self.cubie_18.setSizePolicy(sizePolicy)
        self.cubie_18.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_18.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_18.setStyleSheet("background-color:white;\n"
"")
        self.cubie_18.setObjectName("cubie_18")
        self.gridLayout_3.addWidget(self.cubie_18, 0, 0, 1, 1)
        self.cubie_24 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_24.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_24.sizePolicy().hasHeightForWidth())
        self.cubie_24.setSizePolicy(sizePolicy)
        self.cubie_24.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_24.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_24.setStyleSheet("background-color:white;\n"
"")
        self.cubie_24.setObjectName("cubie_24")
        self.gridLayout_3.addWidget(self.cubie_24, 2, 0, 1, 1)
        self.cubie_25 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_25.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_25.sizePolicy().hasHeightForWidth())
        self.cubie_25.setSizePolicy(sizePolicy)
        self.cubie_25.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_25.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_25.setStyleSheet("background-color:white;\n"
"")
        self.cubie_25.setObjectName("cubie_25")
        self.gridLayout_3.addWidget(self.cubie_25, 2, 1, 1, 1)
        self.cubie_26 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_26.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_26.sizePolicy().hasHeightForWidth())
        self.cubie_26.setSizePolicy(sizePolicy)
        self.cubie_26.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_26.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_26.setStyleSheet("background-color:white;\n"
"")
        self.cubie_26.setObjectName("cubie_26")
        self.gridLayout_3.addWidget(self.cubie_26, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.cubie_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_8.sizePolicy().hasHeightForWidth())
        self.cubie_8.setSizePolicy(sizePolicy)
        self.cubie_8.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_8.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_8.setStyleSheet("background-color:blue;\n"
"")
        self.cubie_8.setObjectName("cubie_8")
        self.gridLayout.addWidget(self.cubie_8, 2, 2, 1, 1)
        self.cubie_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_0.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_0.sizePolicy().hasHeightForWidth())
        self.cubie_0.setSizePolicy(sizePolicy)
        self.cubie_0.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_0.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_0.setStyleSheet("background-color:blue;\n"
"")
        self.cubie_0.setObjectName("cubie_0")
        self.gridLayout.addWidget(self.cubie_0, 0, 0, 1, 1)
        self.cubie_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_1.sizePolicy().hasHeightForWidth())
        self.cubie_1.setSizePolicy(sizePolicy)
        self.cubie_1.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_1.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_1.setStyleSheet("background-color:blue;\n"
"")
        self.cubie_1.setObjectName("cubie_1")
        self.gridLayout.addWidget(self.cubie_1, 0, 1, 1, 1)
        self.cubie_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_2.sizePolicy().hasHeightForWidth())
        self.cubie_2.setSizePolicy(sizePolicy)
        self.cubie_2.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_2.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_2.setStyleSheet("background-color:blue;\n"
"")
        self.cubie_2.setObjectName("cubie_2")
        self.gridLayout.addWidget(self.cubie_2, 0, 2, 1, 1)
        self.cubie_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_3.sizePolicy().hasHeightForWidth())
        self.cubie_3.setSizePolicy(sizePolicy)
        self.cubie_3.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_3.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_3.setStyleSheet("background-color:blue;\n"
"")
        self.cubie_3.setObjectName("cubie_3")
        self.gridLayout.addWidget(self.cubie_3, 1, 0, 1, 1)
        self.cubie_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_4.sizePolicy().hasHeightForWidth())
        self.cubie_4.setSizePolicy(sizePolicy)
        self.cubie_4.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_4.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_4.setStyleSheet("background-color:blue;\n"
"")
        self.cubie_4.setObjectName("cubie_4")
        self.gridLayout.addWidget(self.cubie_4, 1, 1, 1, 1)
        self.cubie_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_5.sizePolicy().hasHeightForWidth())
        self.cubie_5.setSizePolicy(sizePolicy)
        self.cubie_5.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_5.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_5.setStyleSheet("background-color:blue;\n"
"")
        self.cubie_5.setObjectName("cubie_5")
        self.gridLayout.addWidget(self.cubie_5, 1, 2, 1, 1)
        self.cubie_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_6.sizePolicy().hasHeightForWidth())
        self.cubie_6.setSizePolicy(sizePolicy)
        self.cubie_6.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_6.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_6.setStyleSheet("background-color:blue;\n"
"")
        self.cubie_6.setObjectName("cubie_6")
        self.gridLayout.addWidget(self.cubie_6, 2, 0, 1, 1)
        self.cubie_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_7.sizePolicy().hasHeightForWidth())
        self.cubie_7.setSizePolicy(sizePolicy)
        self.cubie_7.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_7.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_7.setStyleSheet("background-color:blue;\n"
"")
        self.cubie_7.setObjectName("cubie_7")
        self.gridLayout.addWidget(self.cubie_7, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cubie_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_9.sizePolicy().hasHeightForWidth())
        self.cubie_9.setSizePolicy(sizePolicy)
        self.cubie_9.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_9.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_9.setStyleSheet("background-color:orange;\n"
"")
        self.cubie_9.setObjectName("cubie_9")
        self.gridLayout_2.addWidget(self.cubie_9, 0, 0, 1, 1)
        self.cubie_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_11.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_11.sizePolicy().hasHeightForWidth())
        self.cubie_11.setSizePolicy(sizePolicy)
        self.cubie_11.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_11.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_11.setStyleSheet("background-color:orange;\n"
"")
        self.cubie_11.setObjectName("cubie_11")
        self.gridLayout_2.addWidget(self.cubie_11, 0, 2, 1, 1)
        self.cubie_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_12.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_12.sizePolicy().hasHeightForWidth())
        self.cubie_12.setSizePolicy(sizePolicy)
        self.cubie_12.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_12.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_12.setStyleSheet("background-color:orange;\n"
"")
        self.cubie_12.setObjectName("cubie_12")
        self.gridLayout_2.addWidget(self.cubie_12, 1, 0, 1, 1)
        self.cubie_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_10.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_10.sizePolicy().hasHeightForWidth())
        self.cubie_10.setSizePolicy(sizePolicy)
        self.cubie_10.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_10.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_10.setStyleSheet("background-color:orange;\n"
"")
        self.cubie_10.setObjectName("cubie_10")
        self.gridLayout_2.addWidget(self.cubie_10, 0, 1, 1, 1)
        self.cubie_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_14.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_14.sizePolicy().hasHeightForWidth())
        self.cubie_14.setSizePolicy(sizePolicy)
        self.cubie_14.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_14.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_14.setStyleSheet("background-color:orange;\n"
"")
        self.cubie_14.setObjectName("cubie_14")
        self.gridLayout_2.addWidget(self.cubie_14, 1, 2, 1, 1)
        self.cubie_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_13.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_13.sizePolicy().hasHeightForWidth())
        self.cubie_13.setSizePolicy(sizePolicy)
        self.cubie_13.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_13.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_13.setStyleSheet("background-color:orange;\n"
"")
        self.cubie_13.setObjectName("cubie_13")
        self.gridLayout_2.addWidget(self.cubie_13, 1, 1, 1, 1)
        self.cubie_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_15.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_15.sizePolicy().hasHeightForWidth())
        self.cubie_15.setSizePolicy(sizePolicy)
        self.cubie_15.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_15.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_15.setStyleSheet("background-color:orange;\n"
"")
        self.cubie_15.setObjectName("cubie_15")
        self.gridLayout_2.addWidget(self.cubie_15, 2, 0, 1, 1)
        self.cubie_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_16.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_16.sizePolicy().hasHeightForWidth())
        self.cubie_16.setSizePolicy(sizePolicy)
        self.cubie_16.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_16.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_16.setStyleSheet("background-color:orange;\n"
"")
        self.cubie_16.setObjectName("cubie_16")
        self.gridLayout_2.addWidget(self.cubie_16, 2, 1, 1, 1)
        self.cubie_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_17.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_17.sizePolicy().hasHeightForWidth())
        self.cubie_17.setSizePolicy(sizePolicy)
        self.cubie_17.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_17.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_17.setStyleSheet("background-color:orange;\n"
"")
        self.cubie_17.setObjectName("cubie_17")
        self.gridLayout_2.addWidget(self.cubie_17, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cubie_37 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_37.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_37.sizePolicy().hasHeightForWidth())
        self.cubie_37.setSizePolicy(sizePolicy)
        self.cubie_37.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_37.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_37.setStyleSheet("background-color:yellow;\n"
"")
        self.cubie_37.setObjectName("cubie_37")
        self.gridLayout_5.addWidget(self.cubie_37, 0, 1, 1, 1)
        self.cubie_38 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_38.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_38.sizePolicy().hasHeightForWidth())
        self.cubie_38.setSizePolicy(sizePolicy)
        self.cubie_38.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_38.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_38.setStyleSheet("background-color:yellow;\n"
"")
        self.cubie_38.setObjectName("cubie_38")
        self.gridLayout_5.addWidget(self.cubie_38, 0, 2, 1, 1)
        self.cubie_40 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_40.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_40.sizePolicy().hasHeightForWidth())
        self.cubie_40.setSizePolicy(sizePolicy)
        self.cubie_40.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_40.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_40.setStyleSheet("background-color:yellow;\n"
"")
        self.cubie_40.setObjectName("cubie_40")
        self.gridLayout_5.addWidget(self.cubie_40, 1, 1, 1, 1)
        self.cubie_39 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_39.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_39.sizePolicy().hasHeightForWidth())
        self.cubie_39.setSizePolicy(sizePolicy)
        self.cubie_39.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_39.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_39.setStyleSheet("background-color:yellow;\n"
"")
        self.cubie_39.setObjectName("cubie_39")
        self.gridLayout_5.addWidget(self.cubie_39, 1, 0, 1, 1)
        self.cubie_41 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_41.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_41.sizePolicy().hasHeightForWidth())
        self.cubie_41.setSizePolicy(sizePolicy)
        self.cubie_41.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_41.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_41.setStyleSheet("background-color:yellow;\n"
"")
        self.cubie_41.setObjectName("cubie_41")
        self.gridLayout_5.addWidget(self.cubie_41, 1, 2, 1, 1)
        self.cubie_36 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_36.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_36.sizePolicy().hasHeightForWidth())
        self.cubie_36.setSizePolicy(sizePolicy)
        self.cubie_36.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_36.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_36.setStyleSheet("background-color:yellow;\n"
"")
        self.cubie_36.setObjectName("cubie_36")
        self.gridLayout_5.addWidget(self.cubie_36, 0, 0, 1, 1)
        self.cubie_42 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_42.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_42.sizePolicy().hasHeightForWidth())
        self.cubie_42.setSizePolicy(sizePolicy)
        self.cubie_42.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_42.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_42.setStyleSheet("background-color:yellow;\n"
"")
        self.cubie_42.setObjectName("cubie_42")
        self.gridLayout_5.addWidget(self.cubie_42, 2, 0, 1, 1)
        self.cubie_43 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_43.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_43.sizePolicy().hasHeightForWidth())
        self.cubie_43.setSizePolicy(sizePolicy)
        self.cubie_43.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_43.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_43.setStyleSheet("background-color:yellow;\n"
"")
        self.cubie_43.setObjectName("cubie_43")
        self.gridLayout_5.addWidget(self.cubie_43, 2, 1, 1, 1)
        self.cubie_44 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_44.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_44.sizePolicy().hasHeightForWidth())
        self.cubie_44.setSizePolicy(sizePolicy)
        self.cubie_44.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_44.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_44.setStyleSheet("background-color:yellow;\n"
"")
        self.cubie_44.setObjectName("cubie_44")
        self.gridLayout_5.addWidget(self.cubie_44, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 1, 3, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cubie_28 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_28.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_28.sizePolicy().hasHeightForWidth())
        self.cubie_28.setSizePolicy(sizePolicy)
        self.cubie_28.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_28.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_28.setStyleSheet("background-color:red;\n"
"")
        self.cubie_28.setObjectName("cubie_28")
        self.gridLayout_4.addWidget(self.cubie_28, 0, 1, 1, 1)
        self.cubie_30 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_30.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_30.sizePolicy().hasHeightForWidth())
        self.cubie_30.setSizePolicy(sizePolicy)
        self.cubie_30.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_30.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_30.setStyleSheet("background-color:red;\n"
"")
        self.cubie_30.setObjectName("cubie_30")
        self.gridLayout_4.addWidget(self.cubie_30, 1, 0, 1, 1)
        self.cubie_29 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_29.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_29.sizePolicy().hasHeightForWidth())
        self.cubie_29.setSizePolicy(sizePolicy)
        self.cubie_29.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_29.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_29.setStyleSheet("background-color:red;\n"
"")
        self.cubie_29.setObjectName("cubie_29")
        self.gridLayout_4.addWidget(self.cubie_29, 0, 2, 1, 1)
        self.cubie_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_31.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_31.sizePolicy().hasHeightForWidth())
        self.cubie_31.setSizePolicy(sizePolicy)
        self.cubie_31.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_31.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_31.setStyleSheet("background-color:red;\n"
"")
        self.cubie_31.setObjectName("cubie_31")
        self.gridLayout_4.addWidget(self.cubie_31, 1, 1, 1, 1)
        self.cubie_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_32.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_32.sizePolicy().hasHeightForWidth())
        self.cubie_32.setSizePolicy(sizePolicy)
        self.cubie_32.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_32.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_32.setStyleSheet("background-color:red;\n"
"")
        self.cubie_32.setObjectName("cubie_32")
        self.gridLayout_4.addWidget(self.cubie_32, 1, 2, 1, 1)
        self.cubie_27 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_27.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_27.sizePolicy().hasHeightForWidth())
        self.cubie_27.setSizePolicy(sizePolicy)
        self.cubie_27.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_27.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_27.setStyleSheet("background-color:red;\n"
"")
        self.cubie_27.setObjectName("cubie_27")
        self.gridLayout_4.addWidget(self.cubie_27, 0, 0, 1, 1)
        self.cubie_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_33.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_33.sizePolicy().hasHeightForWidth())
        self.cubie_33.setSizePolicy(sizePolicy)
        self.cubie_33.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_33.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_33.setStyleSheet("background-color:red;\n"
"")
        self.cubie_33.setObjectName("cubie_33")
        self.gridLayout_4.addWidget(self.cubie_33, 2, 0, 1, 1)
        self.cubie_34 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_34.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_34.sizePolicy().hasHeightForWidth())
        self.cubie_34.setSizePolicy(sizePolicy)
        self.cubie_34.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_34.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_34.setStyleSheet("background-color:red;\n"
"")
        self.cubie_34.setObjectName("cubie_34")
        self.gridLayout_4.addWidget(self.cubie_34, 2, 1, 1, 1)
        self.cubie_35 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_35.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_35.sizePolicy().hasHeightForWidth())
        self.cubie_35.setSizePolicy(sizePolicy)
        self.cubie_35.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_35.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_35.setStyleSheet("background-color:red;\n"
"")
        self.cubie_35.setObjectName("cubie_35")
        self.gridLayout_4.addWidget(self.cubie_35, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 1, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cubie_47 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_47.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_47.sizePolicy().hasHeightForWidth())
        self.cubie_47.setSizePolicy(sizePolicy)
        self.cubie_47.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_47.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_47.setStyleSheet("background-color:green;\n"
"")
        self.cubie_47.setObjectName("cubie_47")
        self.gridLayout_6.addWidget(self.cubie_47, 0, 2, 1, 1)
        self.cubie_45 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_45.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_45.sizePolicy().hasHeightForWidth())
        self.cubie_45.setSizePolicy(sizePolicy)
        self.cubie_45.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_45.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_45.setStyleSheet("background-color:green;\n"
"")
        self.cubie_45.setObjectName("cubie_45")
        self.gridLayout_6.addWidget(self.cubie_45, 0, 0, 1, 1)
        self.cubie_46 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_46.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_46.sizePolicy().hasHeightForWidth())
        self.cubie_46.setSizePolicy(sizePolicy)
        self.cubie_46.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_46.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_46.setStyleSheet("background-color:green;\n"
"")
        self.cubie_46.setObjectName("cubie_46")
        self.gridLayout_6.addWidget(self.cubie_46, 0, 1, 1, 1)
        self.cubie_48 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_48.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_48.sizePolicy().hasHeightForWidth())
        self.cubie_48.setSizePolicy(sizePolicy)
        self.cubie_48.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_48.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_48.setStyleSheet("background-color:green;\n"
"")
        self.cubie_48.setObjectName("cubie_48")
        self.gridLayout_6.addWidget(self.cubie_48, 1, 0, 1, 1)
        self.cubie_50 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_50.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_50.sizePolicy().hasHeightForWidth())
        self.cubie_50.setSizePolicy(sizePolicy)
        self.cubie_50.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_50.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_50.setStyleSheet("background-color:green;\n"
"")
        self.cubie_50.setObjectName("cubie_50")
        self.gridLayout_6.addWidget(self.cubie_50, 1, 2, 1, 1)
        self.cubie_49 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_49.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_49.sizePolicy().hasHeightForWidth())
        self.cubie_49.setSizePolicy(sizePolicy)
        self.cubie_49.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_49.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_49.setStyleSheet("background-color:green;\n"
"")
        self.cubie_49.setObjectName("cubie_49")
        self.gridLayout_6.addWidget(self.cubie_49, 1, 1, 1, 1)
        self.cubie_51 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_51.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_51.sizePolicy().hasHeightForWidth())
        self.cubie_51.setSizePolicy(sizePolicy)
        self.cubie_51.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_51.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_51.setStyleSheet("background-color:green;\n"
"")
        self.cubie_51.setObjectName("cubie_51")
        self.gridLayout_6.addWidget(self.cubie_51, 2, 0, 1, 1)
        self.cubie_52 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_52.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_52.sizePolicy().hasHeightForWidth())
        self.cubie_52.setSizePolicy(sizePolicy)
        self.cubie_52.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_52.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_52.setStyleSheet("background-color:green;\n"
"")
        self.cubie_52.setObjectName("cubie_52")
        self.gridLayout_6.addWidget(self.cubie_52, 2, 1, 1, 1)
        self.cubie_53 = QtWidgets.QLineEdit(self.centralwidget)
        self.cubie_53.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubie_53.sizePolicy().hasHeightForWidth())
        self.cubie_53.setSizePolicy(sizePolicy)
        self.cubie_53.setMinimumSize(QtCore.QSize(50, 50))
        self.cubie_53.setMaximumSize(QtCore.QSize(50, 50))
        self.cubie_53.setStyleSheet("background-color:green;\n"
"")
        self.cubie_53.setObjectName("cubie_53")
        self.gridLayout_6.addWidget(self.cubie_53, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.btn_up = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_up.sizePolicy().hasHeightForWidth())
        self.btn_up.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_up.setFont(font)
        self.btn_up.setStyleSheet("background-color:blue;\n"
"")
        self.btn_up.setObjectName("btn_up")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btn_up)
        self.btn_up_reverse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_up_reverse.sizePolicy().hasHeightForWidth())
        self.btn_up_reverse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_up_reverse.setFont(font)
        self.btn_up_reverse.setStyleSheet("background-color:blue;\n"
"")
        self.btn_up_reverse.setObjectName("btn_up_reverse")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btn_up_reverse)
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_left.setFont(font)
        self.btn_left.setStyleSheet("background-color:orange;\n"
"")
        self.btn_left.setObjectName("btn_left")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_left)
        self.btn_left_reverse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_left_reverse.sizePolicy().hasHeightForWidth())
        self.btn_left_reverse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_left_reverse.setFont(font)
        self.btn_left_reverse.setStyleSheet("background-color:orange;\n"
"")
        self.btn_left_reverse.setObjectName("btn_left_reverse")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btn_left_reverse)
        self.btn_front = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_front.setFont(font)
        self.btn_front.setStyleSheet("background-color:white;\n"
"")
        self.btn_front.setObjectName("btn_front")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.btn_front)
        self.btn_front_reverse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_front_reverse.sizePolicy().hasHeightForWidth())
        self.btn_front_reverse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_front_reverse.setFont(font)
        self.btn_front_reverse.setStyleSheet("background-color:white;\n"
"")
        self.btn_front_reverse.setObjectName("btn_front_reverse")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_front_reverse)
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_right.setFont(font)
        self.btn_right.setStyleSheet("background-color:red;\n"
"")
        self.btn_right.setObjectName("btn_right")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.btn_right)
        self.btn_right_reverse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_right_reverse.sizePolicy().hasHeightForWidth())
        self.btn_right_reverse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_right_reverse.setFont(font)
        self.btn_right_reverse.setStyleSheet("background-color:red;\n"
"")
        self.btn_right_reverse.setObjectName("btn_right_reverse")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_right_reverse)
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("background-color:yellow;\n"
"")
        self.btn_back.setObjectName("btn_back")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.btn_back)
        self.btn_back_reverse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_reverse.sizePolicy().hasHeightForWidth())
        self.btn_back_reverse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_back_reverse.setFont(font)
        self.btn_back_reverse.setStyleSheet("background-color:yellow;\n"
"")
        self.btn_back_reverse.setObjectName("btn_back_reverse")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btn_back_reverse)
        self.btn_down = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_down.setFont(font)
        self.btn_down.setStyleSheet("background-color:green;\n"
"")
        self.btn_down.setObjectName("btn_down")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.btn_down)
        self.btn_down_reverse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_down_reverse.sizePolicy().hasHeightForWidth())
        self.btn_down_reverse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_down_reverse.setFont(font)
        self.btn_down_reverse.setStyleSheet("background-color:green;\n"
"")
        self.btn_down_reverse.setObjectName("btn_down_reverse")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btn_down_reverse)
        self.verticalLayout_11.addLayout(self.formLayout)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem10)
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reset.setFont(font)
        self.btn_reset.setStyleSheet("background-color:black;color:white;\n"
"")
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_26.addWidget(self.btn_reset)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem11)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem12)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 10)
        self.verticalLayout_11.setStretch(2, 2)
        self.verticalLayout_11.setStretch(3, 2)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.line_actions = QtWidgets.QLineEdit(self.centralwidget)
        self.line_actions.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_actions.setFont(font)
        self.line_actions.setAlignment(QtCore.Qt.AlignCenter)
        self.line_actions.setObjectName("line_actions")
        self.horizontalLayout_2.addWidget(self.line_actions)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 18)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem17)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_solve = QtWidgets.QPushButton(self.centralwidget)
        self.btn_solve.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_solve.setFont(font)
        self.btn_solve.setObjectName("btn_solve")
        self.verticalLayout_8.addWidget(self.btn_solve)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem18)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.horizontalLayout_30.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.line_solve_threshold = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_solve_threshold.setFont(font)
        self.line_solve_threshold.setMaxLength(4)
        self.line_solve_threshold.setPlaceholderText("")
        self.line_solve_threshold.setObjectName("line_solve_threshold")
        self.verticalLayout_9.addWidget(self.line_solve_threshold)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem19)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1)
        self.horizontalLayout_30.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radio_second = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_second.setFont(font)
        self.radio_second.setChecked(True)
        self.radio_second.setObjectName("radio_second")
        self.verticalLayout_10.addWidget(self.radio_second)
        self.radio_iter = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_iter.setFont(font)
        self.radio_iter.setObjectName("radio_iter")
        self.verticalLayout_10.addWidget(self.radio_iter)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout_10.setStretch(1, 1)
        self.horizontalLayout_30.addLayout(self.verticalLayout_10)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem20)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem21)
        self.btn_scramble = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scramble.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_scramble.setFont(font)
        self.btn_scramble.setObjectName("btn_scramble")
        self.horizontalLayout_25.addWidget(self.btn_scramble)
        self.line_scramble_depth = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_scramble_depth.setFont(font)
        self.line_scramble_depth.setMaxLength(3)
        self.line_scramble_depth.setObjectName("line_scramble_depth")
        self.horizontalLayout_25.addWidget(self.line_scramble_depth)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem22)
        self.verticalLayout_13.addLayout(self.horizontalLayout_25)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem23)
        self.verticalLayout_13.setStretch(0, 1)
        self.verticalLayout_13.setStretch(1, 1)
        self.horizontalLayout_30.addLayout(self.verticalLayout_13)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem24)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem25)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem26)
        self.btn_settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_settings.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_settings.setFont(font)
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout_22.addWidget(self.btn_settings)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem27)
        self.horizontalLayout_22.setStretch(0, 4)
        self.horizontalLayout_22.setStretch(1, 4)
        self.horizontalLayout_22.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem28)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.settings = widgets_utils.Settings(search_weight=conf.weight,
                                          search_batch_size=conf.batch_size)
        self.net = getNetwork(conf.network_type)
        device = torch.device("cpu")
        self.net = self.net(54 * 6).to(device)
        self.net.load_state_dict(torch.load(conf.heuristic_path, map_location=device))

        self.astar = AStar(weight=conf.weight, max_iter=None, max_time=None, batch_size=conf.batch_size)

        self.COLOR_VALUE = {"blue": 0, "orange": 1, "white": 2, "red": 3, "yellow": 4, "green": 5}
        self.VALUE_COLOR = ["blue", "orange", "white", "red", "yellow", "green"]

        self.cubies = []
        for i in range(3):
                for j in range(3):
                        temp = self.gridLayout_7.itemAtPosition(0, 1).itemAtPosition(i, j).widget()
                        self.cubies.append([temp, temp.styleSheet().split(":")[1][:-2]])

        for i in range(4):
                for j in range(3):
                        for k in range(3):
                                temp = self.gridLayout_7.itemAtPosition(1, i).itemAtPosition(j, k).widget()
                                self.cubies.append([temp, temp.styleSheet().split(":")[1][:-2]])

        for i in range(3):
                for j in range(3):
                        temp = self.gridLayout_7.itemAtPosition(2, 1).itemAtPosition(i, j).widget()
                        self.cubies.append([temp, temp.styleSheet().split(":")[1][:-2]])


        self.line_scramble_depth.setValidator(QIntValidator())
        self.line_solve_threshold.setValidator(QIntValidator())
        self.btn_scramble.clicked.connect(self.scramble)
        self.btn_reset.clicked.connect(self.reset)
        self.btn_solve.clicked.connect(self.solve)

        self.manual_buttons = []
        self.btn_up.clicked.connect(lambda: self.scramble(seq=[0]))
        self.manual_buttons.append(self.btn_up)
        self.btn_up_reverse.clicked.connect(lambda: self.scramble(seq=[6]))
        self.manual_buttons.append(self.btn_up_reverse)
        self.btn_left.clicked.connect(lambda: self.scramble(seq=[1]))
        self.manual_buttons.append(self.btn_left)
        self.btn_left_reverse.clicked.connect(lambda: self.scramble(seq=[7]))
        self.manual_buttons.append(self.btn_left_reverse)
        self.btn_front.clicked.connect(lambda: self.scramble(seq=[2]))
        self.manual_buttons.append(self.btn_front)
        self.btn_front_reverse.clicked.connect(lambda: self.scramble(seq=[8]))
        self.manual_buttons.append(self.btn_front_reverse)
        self.btn_right.clicked.connect(lambda: self.scramble(seq=[3]))
        self.manual_buttons.append(self.btn_right)
        self.btn_right_reverse.clicked.connect(lambda: self.scramble(seq=[9]))
        self.manual_buttons.append(self.btn_right_reverse)
        self.btn_back.clicked.connect(lambda: self.scramble(seq=[4]))
        self.manual_buttons.append(self.btn_back)
        self.btn_back_reverse.clicked.connect(lambda: self.scramble(seq=[10]))
        self.manual_buttons.append(self.btn_back_reverse)
        self.btn_down.clicked.connect(lambda: self.scramble(seq=[5]))
        self.manual_buttons.append(self.btn_down)
        self.btn_down_reverse.clicked.connect(lambda: self.scramble(seq=[11]))
        self.manual_buttons.append(self.btn_down_reverse)
        self.btn_settings.clicked.connect(self.open_settings)
        self.settings_dialog = Ui_SettingsDialog(self.settings)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def open_settings(self):
        self.settings_dialog.exec_()
        self.settings_dialog = Ui_SettingsDialog(self.settings)

    def solve(self):
        self.btn_reset.setEnabled(False)
        self.btn_scramble.setEnabled(False)
        self.btn_solve.setEnabled(False)

        if self.radio_second.isChecked():
            threshold = self.line_solve_threshold.text() or self.settings.def_time
            threshold = int(threshold)
            self.astar.set_max_time(threshold)
        else:
            threshold = self.line_solve_threshold.text() or self.settings.def_iter
            threshold = int(threshold)
            self.astar.set_max_iter(threshold)
        state = widgets_utils.cubies_to_state(self.cubies)
        solved,iteration,nodes,solution = self.astar.search(state,self.net)
        if solved:
            self.scramble(clear_seq(solution))
        else:
            self.line_actions.setText("The cube couldn't be solved. You can increase the time or iteration limit.")
        self.btn_reset.setEnabled(True)
        self.btn_scramble.setEnabled(True)
        self.btn_solve.setEnabled(True)
        [button.setEnabled(True) for button in self.manual_buttons]
    def reset(self):
        self.line_actions.clear()
        self.line_scramble_depth.clear()
        self.line_solve_threshold.clear()
        self.btn_solve.setEnabled(True)
        solved = cube.get_solved()
        for idx, value in enumerate(solved):
            self.cubies[idx][0].setStyleSheet(f"""background-color:{self.VALUE_COLOR[value]};\n""")
            self.cubies[idx][1] = self.VALUE_COLOR[value]

    def scramble(self,seq=None):
        if not seq:
            depth = self.line_scramble_depth.text() or self.settings.def_scramble_depth
            self.line_scramble_depth.clear()
            depth = int(depth)
            self.states, self.seq = widgets_utils.scramble(self.cubies, depth=depth)
        else:
            self.states, self.seq = widgets_utils.scramble(self.cubies, seq=seq)
        self.btn_reset.setEnabled(False)
        self.btn_scramble.setEnabled(False)
        self.btn_solve.setEnabled(False)
        [button.setEnabled(False) for button in self.manual_buttons]
        string_seq = widgets_utils.seq_to_string(self.seq)
        self.line_actions.setVisible(True)
        self.line_actions.setText(string_seq)
        self.i = 0
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.act)
        self.timer.start(self.settings.actions_delay)

    def act(self):
        if self.i == len(self.states):
            self.timer.stop()
            self.btn_reset.setEnabled(True)
            self.btn_scramble.setEnabled(True)
            self.btn_solve.setEnabled(True)
            [button.setEnabled(True) for button in self.manual_buttons]
        else:

            for idx, value in enumerate(self.states[self.i]):
                self.cubies[idx][0].setStyleSheet(f"""background-color:{self.VALUE_COLOR[value]};\n""")
                self.cubies[idx][1]=self.VALUE_COLOR[value]
            self.i+=1

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_up.setText(_translate("MainWindow", "U"))
        self.btn_up_reverse.setText(_translate("MainWindow", "U\'"))
        self.btn_left.setText(_translate("MainWindow", "L"))
        self.btn_left_reverse.setText(_translate("MainWindow", "L\'"))
        self.btn_front.setText(_translate("MainWindow", "F"))
        self.btn_front_reverse.setText(_translate("MainWindow", "F\'"))
        self.btn_right.setText(_translate("MainWindow", "R"))
        self.btn_right_reverse.setText(_translate("MainWindow", "R\'"))
        self.btn_back.setText(_translate("MainWindow", "B"))
        self.btn_back_reverse.setText(_translate("MainWindow", "B\'"))
        self.btn_down.setText(_translate("MainWindow", "D"))
        self.btn_down_reverse.setText(_translate("MainWindow", "D\'"))
        self.btn_reset.setText(_translate("MainWindow", "RESET"))
        self.btn_solve.setText(_translate("MainWindow", "Try to Solve in"))
        self.radio_second.setText(_translate("MainWindow", "seconds."))
        self.radio_iter.setText(_translate("MainWindow", "iterations."))
        self.btn_scramble.setText(_translate("MainWindow", "Scramble"))
        self.line_scramble_depth.setPlaceholderText(_translate("MainWindow", "Depth"))
        self.btn_settings.setText(_translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
